export const POPULAR_BRANDS = [
  'Hatchbox',
  'eSUN',
  'Overture',
  'Polymaker',
  'Prusament',
  'Amazon Basics',
  'Sunlu',
  'Creality',
  'Eryone',
  'TTYT3D',
  'Inland',
  'MatterHackers',
  'ColorFabb',
  'Fillamentum',
  'FormFutura',
  'Proto-pasta',
  'Push Plastic',
  'Atomic Filament',
  '3D Solutech',
  'Duramic',
  'ZIRO',
  'Geeetech',
  'YOYI',
  'PRILINE',
  'Bambu Lab',
  'Anycubic',
  'Elegoo',
]
